project:
  title: 'Web project' # Project title
  type: website
  execute-dir: project
  render:
    - index.qmd
    - process/1_acquire.qmd
    - process/2_curate.qmd
    - process/3_transform.qmd
    - process/4_analyze.qmd
    - reports/
website:
  page-navigation: true # Enable page navigation
  reader-mode: true # Enable reader mode
  site-url: 'https://username.github.io/repo' # Website URL
  repo-url: https://github.com/username/repo # Repository URL
  repo-actions: [source, issue] # Repository actions
  repo-link-target: '_blank' # Open repository links in a new tab
  sidebar:
    style: 'docked' # Sidebar style
    search: true # Enable search
    collapse-level: 2 # Initial sidebar collapse level
    contents: # Sidebar contents
      - index.qmd
      - section: 'Process'
        contents: process/*
      - section: 'Reports'
        contents: reports/*
    tools:
      - icon: github
        href: https:://github.com
bibliography: bibliography.bib # Bibliography file
format:
  html:
    theme: cosmo # Bootstrap theme for the site
    toc: true # Enable table of contents
execute:
  freeze: auto # only render documents that have changed
